# Generated by Django 4.2 on 2026-01-09 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('CONFIRMED', 'Подтверждена'), ('IN_PROGRESS', 'В работе'), ('COMPLETED', 'Завершена'), ('CANCELLED', 'Отменена'), ('NO_SHOW', 'Не явился')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('date', models.DateField(verbose_name='Дата приема')),
                ('time', models.TimeField(verbose_name='Время приема')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Запись на прием',
                'verbose_name_plural': 'Записи на прием',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отделения')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email адрес')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='branches/', verbose_name='Фото отделения')),
                ('work_schedule', models.TextField(verbose_name='График работы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступна в отделении')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления доступности')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_services', to='mfc.branch', verbose_name='Отделение')),
            ],
            options={
                'verbose_name': 'Доступность услуги в отделении',
                'verbose_name_plural': 'Доступность услуг в отделениях',
                'ordering': ['branch__name', 'service__name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('employee', 'Сотрудник МФЦ'), ('admin', 'Администратор системы')], default='client', max_length=20, verbose_name='Роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('category', models.CharField(choices=[('DOC', 'Документы и справки'), ('PROP', 'Недвижимость и земля'), ('TRANS', 'Транспорт и водительские права'), ('SOC', 'Социальные услуги'), ('BUS', 'Бизнес и предпринимательство'), ('HLTH', 'Здравоохранение'), ('EDU', 'Образование'), ('OTHER', 'Прочее')], default='OTHER', max_length=10, verbose_name='Категория')),
                ('duration_days', models.PositiveIntegerField(default=14, help_text='Сколько дней занимает оказание услуги', verbose_name='Срок выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('branches', models.ManyToManyField(blank=True, related_name='services', through='mfc.BranchService', to='mfc.branch', verbose_name='Доступна в отделениях')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('specialist', 'Специалист приема'), ('consultant', 'Консультант'), ('admin', 'Администратор отделения')], default='specialist', help_text='Должность сотрудника МФЦ', max_length=50, verbose_name='Должность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата приема на работу')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения данных')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='mfc.branch', verbose_name='Отделение МФЦ')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='mfc.userprofile', verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Сотрудник МФЦ',
                'verbose_name_plural': 'Сотрудники МФЦ',
                'ordering': ['user_profile__full_name'],
            },
        ),
        migrations.AddField(
            model_name='branchservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_services', to='mfc.service', verbose_name='Услуга'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['-created_at'], name='mfc_branch_created_212e60_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_active'], name='mfc_branch_is_acti_d07a1d_idx'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='mfc.branch', verbose_name='Отделение'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='mfc.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='mfc.userprofile', verbose_name='Профиль пользователя'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['role'], name='mfc_userpro_role_e8244b_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['email'], name='mfc_userpro_email_1f6750_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['created_at'], name='mfc_userpro_created_e27432_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='mfc_service_categor_facf03_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position'], name='mfc_employe_positio_927121_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['office'], name='mfc_employe_office__27838b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user_profile'], name='mfc_employe_user_pr_fe6ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='branchservice',
            index=models.Index(fields=['branch'], name='mfc_branchs_branch__d8fa23_idx'),
        ),
        migrations.AddIndex(
            model_name='branchservice',
            index=models.Index(fields=['service'], name='mfc_branchs_service_0f7c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='branchservice',
            index=models.Index(fields=['branch', 'is_available'], name='mfc_branchs_branch__24f807_idx'),
        ),
        migrations.AddIndex(
            model_name='branchservice',
            index=models.Index(fields=['service', 'is_available'], name='mfc_branchs_service_986542_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branchservice',
            unique_together={('branch', 'service')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='mfc_appoint_status_a8bb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date'], name='mfc_appoint_date_b266f3_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['user_profile'], name='mfc_appoint_user_pr_b8a776_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['branch', 'date'], name='mfc_appoint_branch__0b9439_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['branch', 'status', 'date'], name='mfc_appoint_branch__3aa737_idx'),
        ),
    ]
