# Generated by Django 6.0.1 on 2026-01-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0002_historicalappointment_historicalbranch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbranch',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalservice',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalAppointment',
        ),
        migrations.DeleteModel(
            name='HistoricalBranch',
        ),
        migrations.DeleteModel(
            name='HistoricalService',
        ),
    ]
